steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/prakhag1/Java-Test.git']

- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'Java-Test'

- name: 'gcr.io/cloud-builders/mvn'
  args: ['test']
  dir: 'Java-Test'

- name: 'gcr.io/cloud-builders/mvn'
  args: ['verify']
  dir: 'Java-Test'

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/vital-octagon-109612/hello-world", "."]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/vital-octagon-109612/hello-world"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/hello-world-deploy'
  - 'container=gcr.io/vital-octagon-109612/hello-world:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test123'

